FROM i386/alpine:3.9 as builder

ARG QEMU_USER_STATIC_ARCH

COPY qemu-${QEMU_USER_STATIC_ARCH}-static /usr/bin/

RUN apk update \
 && apk add dhcp dhcp-doc perl dumb-init mdocml \
 && rm /usr/bin/qemu-${QEMU_USER_STATIC_ARCH}-static

COPY util/entrypoint.sh /entrypoint.sh

FROM scratch

COPY --from=builder / /

ENTRYPOINT ["/entrypoint.sh"]
