FROM arm32v7/alpine:3.9

COPY qemu-arm-static /usr/bin/

RUN apk update \
 && apk add dhcp dhcp-doc perl dumb-init mdocml \
 && rm /usr/bin/qemu-arm-static

COPY util/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
