#!/bin/bash -x
which jq
mkdir -p ~/.docker
cat << EOF > ~/.docker/config.json
{
    "auths": {
        $(echo ${DOCKERCFG})
    },
    "experimental": "enabled"
}
EOF

curl https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz | tar -xzvf -
chmod -v 755 docker/docker
cp docker/docker /usr/bin/docker

docker manifest inspect ${DOCKER_REPO}:i386-${DOCKER_TAG#*-} &&\
docker manifest inspect ${DOCKER_REPO}:armv7-${DOCKER_TAG#*-} &&\
docker manifest inspect ${DOCKER_REPO}:x86_64-${DOCKER_TAG#*-} &&\
docker manifest create ${DOCKER_REPO}:${DOCKER_TAG#*-} \
${DOCKER_REPO}:i386-${DOCKER_TAG#*-} \
${DOCKER_REPO}:armv7-${DOCKER_TAG#*-} \
${DOCKER_REPO}:x86_64-${DOCKER_TAG#*-} && \
docker manifest annotate --arch 386 ${DOCKER_REPO}:${DOCKER_TAG#*-} \
  ${DOCKER_REPO}:i386-${DOCKER_TAG#*-} &&\
docker manifest annotate --arch arm ${DOCKER_REPO}:${DOCKER_TAG#*-} \
  ${DOCKER_REPO}:armv7-${DOCKER_TAG#*-} &&\
docker manifest push ${DOCKER_REPO}:${DOCKER_TAG#*-}

true
