#!/bin/bash -x
mkdir -p ~/.docker
cat << EOF > ~/.docker/config.json
{
    "experimental": "enabled"
}
EOF

which docker

docker version
cat << EOF > manifest.dockerfile
FROM alpine:3.8
RUN apk add docker bash
EOF

docker build -t manifest:1.0 -f manifest.dockerfile .
docker run -t --rm --name manifest manifest:1.0 ls -l /usr/bin/docker
docker create --rm --name manifest manifest:1.0
docker cp -a manifest:/usr/bin/docker /usr/bin/docker
docker rm manifest
ls -l /usr/bin/docker
which docker
docker version

docker manifest inspect ${DOCKER_REPO}:i386-${DOCKER_TAG#*-} &&\
docker manifest inspect ${DOCKER_REPO}:armv7-${DOCKER_TAG#*-} &&\
docker manifest inspect ${DOCKER_REPO}:x86_64-${DOCKER_TAG#*-} &&\
docker manifest create ${DOCKER_REPO}:${DOCKER_TAG#*-} \
${DOCKER_REPO}:i386-${DOCKER_TAG#*-} \
${DOCKER_REPO}:armv7-${DOCKER_TAG#*-} \
${DOCKER_REPO}:x86_64${DOCKER_TAG#*-} && \
docker manifest annotate --arch 386 ${DOCKER_REPO}:${DOCKER_TAG#*-} \
  ${DOCKER_REPO}:i386-${DOCKER_TAG#*-} &&\
docker manifest annotate --arch arm ${DOCKER_REPO}:${DOCKER_TAG#*-} \
  ${DOCKER_REPO}:armv7-${DOCKER_TAG#*-} &&\
docker manifest push ${DOCKER_REPO}:${DOCKER_TAG#*-}
