#!/bin/bash -x
docker info
echo HOME=${HOME}
[ -d /etc/docker ] && ls -l /etc/docker

[ -f /etc/docker/daemon.json ] && cat /etc/docker/daemon.json

[ -d ~/.docker ] && ls -l ~/.docker

[ -f ~/.docker/config.json ] && cat ~/.docker/config.json

[ -f /etc/default/docker ] && cat /etc/default/docker


env 

cat << EOF > /etc/docker/daemon.json
{
    "experimental": true
}
EOF

mkdir -p ~/.docker
cat << EOF > ~/.docker/config.json
{
    "experimental": "enabled"
}
EOF

systemctl daemon-reload

service docker restart

docker info

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }


docker run --rm --privileged multiarch/qemu-user-static:register --reset