#!/bin/bash -x
BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }

echo HOME=${HOME}

[ -d "~/.docker" ] && ls -l "~/.docker"

[ -f "~/.docker/config.json" ] && cat "~/.docker/config.json"

env 

docker run --rm --privileged multiarch/qemu-user-static:register --reset